# Generated by Django 4.2.6 on 2023-10-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataDrive', '0002_remove_folder_parent_folder_delete_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled Folder', max_length=255)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDrive.employee')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataDrive.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled Folder', max_length=255)),
                ('file', models.FileField(default=False, upload_to='uploads/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDrive.employee')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataDrive.folder')),
            ],
        ),
    ]
