# Generated by Django 4.2.6 on 2023-10-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataDrive', '0003_folder_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDrive.employee'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDrive.employee'),
        ),
    ]
